#!/usr/bin/env bash
# shellcheck disable=SC2034
# This issue is ignored because it is part of a larger file that calls upon all variables listed

# To edit this file copy it to `${HOME}/.config/dmscripts/config`
# `cp /etc/dmscripts/config ${HOME}/.config/dmscripts/config`

# Defined variables, modify anything in quotes to your prefered software

# IMPORTANT! Keep the '-p' flag at the end of the DMENU and RMENU variables.
# Also, keep the '--prompt' flag at the end of the FMENU variable.
# These are needed as we use prompts in the scripts.
DMENU_PYWAL=1
DMENU="dmenu -i -l 20 -p"
RMENU="rofi -dmenu -i -p"
FMENU="fzf --bind=enter:replace-query+print-query --border=rounded --margin=5% --color=dark --height 100% --reverse --header=$(basename "$0") --info=hidden --header-first --prompt"


## DEFAULT PROGRAMS
PDF_VIEWER="zathura"
DMBROWSER="brave"
DMTERM="alacritty -e"
DMEDITOR="emacsclient -c -a emacs"
# DMEDITOR="${DMTERM} vim"
DMLOCKER='betterlockscreen -l blur'

# dmscripts will notify you if your configuration is outdated.
# To shut it up uncomment this line.
# DM_SHUTUP="something" # NOTICE: This is currently experimental and will not work in (most) programs

# Set this variable up to a real file if you want dmscripts to provide a log of when
# and what has changed in your config (this can be an alternative to notifications)
DM_CONFIG_DIFF_LOGFILE="/dev/stderr" # NOTICE: experimental

# This case statement lets you change what the DMENU variable is for different scripts, so if you
# want a unique variable for each script you can
# syntax is as follows:
# "<ending-of-script>") DMENU="your variable here"
# *) should be left blank, global variables are defined above

# include -p in standard dmenu as we use prompts by default
case "${0##*-}" in
#  "colpick") DMENU="dmenu -i -p";;
#  "confedit") DMENU="dmenu -i -l 30 -p";;
#  "youtube") DMBROWSER="firefox";;
  *);;
esac

# "${0##*-}" means grab the 0th argument (which is always the path to the program) starting from the
# last dash. This gives us the word after the - which is what we are searching for in the case
# statement. ie dm-man -> man

# An awk equivalent is: 
# awk -F"-" '{print $NF}'
# Sadly cut has no easy equivalent

# TODO: Move almost all of these variables into the case statement
# TODO: Make some of the more useful ones general variables
# IE a pictures directory, an audio directory, config locations, etc

# dm-bookman 
bookman_show_source=1

# dm-sounds
sounds_dir="${HOME}/.config/dmscripts/dmsounds"

# dm-setbg
setbg_dir="/usr/share/backgrounds/dtos-backgrounds"
# setbg_dir="${HOME}/Pictures/Wallpapers"
# Set this to 1 if you want to use imv and wayland, 0 if you want to use sxiv
# Note that sxiv is X11 only, you need to mark the image you want to use.
use_imv=0 

# dm-maim
maim_dir="${HOME}/Screenshots"
maim_file_prefix="maim"

# dm-note
note_dir="${HOME}/.config/dmscripts/dmnote"


# Search engine config 
declare -Ag websearch
# Syntax:
# websearch[name]="https://www.example.com/search?q="

# Search Engines
websearch[bing]="https://www.bing.com/search?q="
websearch[brave]="https://search.brave.com/search?q="
websearch[duckduckgo]="https://duckduckgo.com/?q="
websearch[gemini search \(https\)]="https://portal.mozz.us/gemini/geminispace.info/search%3F"
websearch[google]="https://www.google.com/search?q="
websearch[qwant]="https://www.qwant.com/?q="
websearch[swisscows]="https://swisscows.com/web?query="
websearch[yandex]="https://yandex.com/search/?text="
# Information/News
websearch[bbcnews]="https://www.bbc.co.uk/search?q="
websearch[cnn]="https://www.cnn.com/search?q="
websearch[googlenews]="https://news.google.com/search?q="
websearch[wikipedia]="https://en.wikipedia.org/w/index.php?search="
websearch[wiktionary]="https://en.wiktionary.org/w/index.php?search="
# Social Media
websearch[reddit]="https://www.reddit.com/search/?q="
websearch[odysee]="https://odysee.com/$/search?q="
websearch[youtube]="https://www.youtube.com/results?search_query="
# Online Shopping
websearch[amazon]="https://www.amazon.com/s?k="
websearch[craigslist]="https://www.craigslist.org/search/sss?query="
websearch[ebay]="https://www.ebay.com/sch/i.html?&_nkw="
websearch[gumtree]="https://www.gumtree.com/search?search_category=all&q="
# Linux
websearch[archaur]="https://aur.archlinux.org/packages/?O=0&K="
websearch[archpkg]="https://archlinux.org/packages/?sort=&q="
websearch[archwiki]="https://wiki.archlinux.org/index.php?search="
websearch[debianpkg]="https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
# Development
websearch[github]="https://github.com/search?q="
websearch[gitlab]="https://gitlab.com/search?search="
websearch[googleOpenSource]="https://opensource.google/projects/search?q="
websearch[sourceforge]="https://sourceforge.net/directory/?q="
websearch[stackoverflow]="https://stackoverflow.com/search?q="
# Etc

# dm-youtube config
# Think of these as your "subscribed channels", name the channel in the square brackets then put the channel URL in the quotation marks
# Syntax: youtube_channels[name]="https://www.youtube.com/link/to/channel"

declare -Ag youtube_channels
youtube_channels[distrotube]="https://www.youtube.com/c/DistroTube/featured"

# dm-radio config
# Your list of online radio stations for the dm-radio script.
# Syntax: radio_stations[name]="https://www.zeno.fm/radio/your-station"
# dmradio-volume ranges between -1 and 100 (for mplayer) or 0-100 (for mpv)

DMRADIOVOLUME="100"
declare -Ag radio_stations
radio_stations[Heart UK]="https://www.globalplayer.com/live/heart/uk/"
radio_stations[Heart 70s]="https://www.globalplayer.com/live/heart70s/uk/"
radio_stations[Heart 80s]="https://www.globalplayer.com/live/heart80s/uk/"
radio_stations[Heart 90s]="https://www.globalplayer.com/live/heart90s/uk/"
radio_stations[Heart 00s]="https://www.globalplayer.com/live/heart00s/uk/"
radio_stations[Heart 10s]="https://www.globalplayer.com/live/heart10s/uk/"
radio_stations[Heart Dance]="https://www.globalplayer.com/live/heartdance/uk/"
radio_stations[Heart Musicals]="https://www.globalplayer.com/live/heartmusicals/uk/"
radio_stations[Heart Love]="https://www.globalplayer.com/live/heartlove/uk/"
radio_stations[Heart Xmas]="https://www.globalplayer.com/live/heartxmas/uk/"
radio_stations[Smooth Radio]="https://www.globalplayer.com/live/smooth/uk/"
radio_stations[Smooth Relax]="https://www.globalplayer.com/live/smoothrelax/uk/"
radio_stations[Smooth Chill]="https://www.globalplayer.com/live/smoothchill/uk/"
radio_stations[Smooth Country]="https://www.globalplayer.com/live/smoothcountry/uk/"
radio_stations[Smooth Soul]="https://www.globalplayer.com/live/smoothsoul/uk/"
radio_stations[Smooth 70s]="https://www.globalplayer.com/live/smooth70s/uk/"
radio_stations[Smooth 80s]="https://www.globalplayer.com/live/smooth80s/uk/"
radio_stations[Smooth Christmas]="https://www.globalplayer.com/live/smoothchristmas/uk/"

# dm-colpick config
declare -Ag colpick_list
colpick_list[black]="#282a36"
colpick_list[red]="#ff5555"
colpick_list[green]="#5af78e"
colpick_list[yellow]="#f1fa8c"
colpick_list[blue]="#57c7ff"
colpick_list[magenta]="#ff6ac1"
colpick_list[cyan]="#8be9fd"
colpick_list[white]="#f1f1f0"
colpick_list[orange]="#ffb86c"
colpick_list[purple]="#bd9cf9"

# dm-weather config

# Example: set the default search parameters to Texas, Paris and Kyiv
# weather_locations="Texas, United States
# Paris, France
# Kyiv, Ukraine"
weather_locations=""

# use the weather_opts variable to set additional flags:
# weather_opts="flag1&flag2&flag3=somevalue"

# for full details see: https://github.com/chubin/wttr.in

# current revision (do not touch unless you know what you're doing)
_revision=27
